FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

# Cambia "PRUEBA_GSE.csproj" si tu archivo .csproj tiene otro nombre
COPY PRUEBA_GSE.csproj ./
RUN dotnet restore "PRUEBA_GSE.csproj"

COPY . .
RUN dotnet build "PRUEBA_GSE.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PRUEBA_GSE.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PRUEBA_GSE.dll"]